### ISSUE TITLE
Publishing status unclear

### ISSUE THREAD

**Issue by ghost** [caioau/caioau-personal#3]
"Comecei a pesquisar e fazer a análise de senhas para um trabalho então resolvi escrever um texto sobre o assunto."

Mas fez o trabalho? Não está claro.

**Comment by caioau** [comment]
@andersbateva o meu grupo acabou optando por um trabalho mais simples e deixamos de lado esse das senhas. e dai nas férias tava atoa , não queria desperdiçar o que tinha feito e escrevi o texto. De toda forma somente o texto está publicado.
