### ISSUE TITLE
JavaScript está presente

### ISSUE THREAD

**Issue by ghost** [caioau/caioau-personal#4]
"ta tranquilo, ta favoravel: meu site é feito usando somente markdown + CSS"

Meu NoScript denunciou que a plataforma keybase que você usou tenta carregar um JavaScript. Não acho que está então tão tranquilo e favorável.

**Comment by caioau** [comment]
obrigado @andersbateva não tinha testado no noscript o site, só no libreJS, mas acho que o site funciona sem habilitar o javascript

**Comment by caioau** [comment]
que estranho @andersbateva pq em outros sites que precisam de javascript, o noscript aparece embaixo que tem scripts que não foram permitidos. Enquanto no meu site ele não aparece, só o iconezinho para liberar os scripts no keybase.pub

**Comment by ghost** [comment]
O site funciona sem JavaScript. Mas o script está presente, talvez como forma de rastreamento dos visitantes mesmo.

**Comment by caioau** [comment]
@andersbateva , investiguei bastante e cheguei a conclusão: o meu site não tem javascript. 

o teste definitivo foi: 
1. clickar com o botão direito no navegador e selecionar inspecionar elemento.
2. vai abrir uma "caixa de ferramentas" selecionar a "aba" rede.
3. entrar no meu site.

serão listados todos os requests que o meu site faz, são apenas requests de html e imagens.

outra hipótese que tive é: eu não coloquei nenhum JS, porém o keybase carrega antes do meu site então carregando um JS, isso não acontece pois teria que ser feito um request tipo o 302.
