### ISSUE TITLE
Naum intendo: distribuição de probabilidade

### ISSUE THREAD

**Issue by ghost** [caioau/caioau-personal#5]
"Def: Dado um espaço amostral de eventos (S), uma distribuição de probabilidade é uma função P, P:S→[0,1], e a única restrição dessa função é que a soma de P aplicada em todos os eventos no espaço amostral vale 1 (caso discreto) e no caso continuo a integral sobre o domínio vale 1."

Não consigo entender isto. Observe que não fiz faculdade de exatas, então não tive aula de cálculo.
Porém, minha intuição me diz que você quer dizer que a probabilidade é um valor entre 0.00 e 1.00, onde 1 = 100% e 0=0%. Ou seja, é o resultado do "%" (divisão por cem) de uma porcentagem. Certo?

**Comment by caioau** [comment]
exato o simbolo "%" é uma "divisão escondida" por 100

**Comment by ghost** [comment]
Era mais fácil simplesmente usar porcentagem :P
