### ISSUE TITLE
Naum intendo: Claudinho Shannon e Buchecha Channel

### ISSUE THREAD

**Issue by ghost** [caioau/caioau-personal#7]
A fórmula da probabilidade de Shannon até está explicada. Mas eu não sei o que diabos é um log, além dos significados "tora" e "registro de histórico".
Observe que não fiz faculdade de exatas, então não tive aula de cálculo.
Devido a não entender isto, não consigo continuar a leitura.

**Comment by caioau** [comment]
obrigado @andersbateva , expliquei no seminário o que é o log e o no contexto da entropia. Na próxima revisão vou colocar no texto.

**Comment by ghost** [comment]
Que seminário?

**Comment by caioau** [comment]
@andersbateva foi no [DivulgaMat](https://divulgamatimeccblog.wordpress.com/) dia 10 de abril
